vim.opt.runtimepath:prepend(vim.fn.getcwd())
vim.opt.runtimepath:append(vim.fn.stdpath("data") .. "/lazy/plenary.nvim")
pcall(function()
  vim.cmd("runtime plugin/plenary.vim")
end)
require("synthwave3000").setup({})
vim.cmd.colorscheme("synthwave3000")
