local function build(p, o)
	local bg = o.transparent and "NONE" or (o.background or p.bg)
	local bg_dark = o.transparent and "NONE" or p.bg_dark
	local bg_darker = o.transparent and "NONE" or p.bg_darker

	return {
		Normal = { fg = p.fg, bg = bg },
		NormalNC = { fg = p.fg, bg = bg },
		NormalFloat = { fg = p.fg, bg = bg_dark },
		FloatBorder = { fg = p.pink, bg = bg_dark },
		FloatTitle = { fg = p.cyan, bg = bg_dark, bold = true },
		FloatFooter = { fg = p.fg_dim, bg = bg_dark },
		ColorColumn = { bg = p.bg_highlight },
		Conceal = { fg = p.comment },
		Cursor = { fg = p.bg, bg = p.fg },
		lCursor = { fg = p.bg, bg = p.pink },
		CursorIM = { fg = p.bg, bg = p.pink },
		CursorColumn = { bg = p.bg_highlight },
		CursorLine = { bg = p.bg_highlight },
		CursorLineNr = { fg = p.pink, bold = true },
		CursorLineFold = { fg = p.comment },
		CursorLineSign = { fg = p.pink },
		Directory = { fg = p.cyan },
		DiffAdd = { fg = p.green, bg = require("synthwave3000.util").blend(p.green, bg, 0.25) },
		DiffChange = { fg = p.yellow, bg = require("synthwave3000.util").blend(p.yellow, bg, 0.25) },
		DiffDelete = { fg = p.red, bg = require("synthwave3000.util").blend(p.red, bg, 0.25) },
		DiffText = { fg = p.cyan, bg = require("synthwave3000.util").blend(p.cyan, bg, 0.35) },
		EndOfBuffer = { fg = bg },
		ErrorMsg = { fg = p.red, bold = true },
		VertSplit = { fg = p.pink },
		WinSeparator = { fg = p.pink },
		Folded = { fg = p.comment, bg = p.bg_highlight },
		FoldColumn = { fg = p.comment, bg = bg_dark },
		SignColumn = { bg = bg_dark },
		IncSearch = { fg = p.bg, bg = p.yellow },
		Substitute = { fg = p.bg, bg = p.orange },
		LineNr = { fg = p.comment },
		LineNrAbove = { fg = p.comment },
		LineNrBelow = { fg = p.comment },
		MatchParen = { fg = p.orange, bold = true },
		ModeMsg = { fg = p.fg, bold = true },
		MoreMsg = { fg = p.cyan, bold = true },
		NonText = { fg = p.comment },
		Pmenu = { fg = p.fg, bg = p.bg_panel },
		PmenuSel = { fg = p.bg, bg = p.pink },
		PmenuSbar = { bg = p.bg_highlight },
		PmenuThumb = { bg = p.selection },
		PmenuKind = { fg = p.cyan, bg = p.bg_panel },
		PmenuKindSel = { fg = p.bg, bg = p.pink },
		PmenuExtra = { fg = p.fg_dim, bg = p.bg_panel },
		PmenuExtraSel = { fg = p.bg, bg = p.pink },
		Question = { fg = p.cyan },
		QuickFixLine = { bg = p.bg_highlight },
		Search = { fg = p.bg, bg = p.cyan },
		CurSearch = { fg = p.bg, bg = p.pink },
		SpecialKey = { fg = p.comment },
		SpellBad = { sp = p.red, undercurl = true },
		SpellCap = { sp = p.yellow, undercurl = true },
		SpellLocal = { sp = p.cyan, undercurl = true },
		SpellRare = { sp = p.pink, undercurl = true },
		StatusLine = { fg = p.fg, bg = bg_dark },
		StatusLineNC = { fg = p.fg_dim, bg = bg_darker },
		StatusLineTerm = { fg = p.fg, bg = bg_dark },
		StatusLineTermNC = { fg = p.fg_dim, bg = bg_darker },
		TabLine = { fg = p.fg_dim, bg = bg_dark },
		TabLineFill = { bg = bg_darker },
		TabLineSel = { fg = p.pink, bg = p.bg, bold = true },
		Title = { fg = p.pink, bold = true },
		Visual = { bg = p.bg_visual },
		VisualNOS = { bg = p.bg_visual },
		WarningMsg = { fg = p.yellow },
		Whitespace = { fg = p.bg_highlight },
		WildMenu = { fg = p.bg, bg = p.pink },
		WinBar = { fg = p.fg, bg = bg_dark },
		WinBarNC = { fg = p.fg_dim, bg = bg_darker },
		MsgArea = { fg = p.fg },
		MsgSeparator = { fg = p.pink },
		FloatShadow = { fg = p.bg_darker },
		FloatShadowThrough = { fg = p.bg_darker },
		Added = { fg = p.green },
		Changed = { fg = p.yellow },
		Removed = { fg = p.red },
	}
end

return { build = build }
