local function build(p, o)
  return {
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.cyan },
    DiagnosticHint = { fg = p.purple },
    DiagnosticOk = { fg = p.green },
    DiagnosticVirtualTextError = { fg = p.red },
    DiagnosticVirtualTextWarn = { fg = p.yellow },
    DiagnosticVirtualTextInfo = { fg = p.cyan },
    DiagnosticVirtualTextHint = { fg = p.purple },
    DiagnosticVirtualTextOk = { fg = p.green },
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.cyan, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.purple, undercurl = true },
    DiagnosticUnderlineOk = { sp = p.green, undercurl = true },
    DiagnosticFloatingError = { fg = p.red },
    DiagnosticFloatingWarn = { fg = p.yellow },
    DiagnosticFloatingInfo = { fg = p.cyan },
    DiagnosticFloatingHint = { fg = p.purple },
    DiagnosticFloatingOk = { fg = p.green },
    DiagnosticSignError = { fg = p.red },
    DiagnosticSignWarn = { fg = p.yellow },
    DiagnosticSignInfo = { fg = p.cyan },
    DiagnosticSignHint = { fg = p.purple },
    DiagnosticSignOk = { fg = p.green },
    DiagnosticDeprecated = { sp = p.red, strikethrough = true },
    DiagnosticUnnecessary = { fg = p.fg_dim },
    ["@lsp.type.class"] = "@type",
    ["@lsp.type.decorator"] = "@function",
    ["@lsp.type.enum"] = "@type",
    ["@lsp.type.enumMember"] = "@constant",
    ["@lsp.type.event"] = "@function",
    ["@lsp.type.function"] = "@function",
    ["@lsp.type.interface"] = "@type",
    ["@lsp.type.keyword"] = "@keyword",
    ["@lsp.type.macro"] = "@function.macro",
    ["@lsp.type.method"] = "@function.method",
    ["@lsp.type.modifier"] = "@keyword.modifier",
    ["@lsp.type.namespace"] = "@module",
    ["@lsp.type.number"] = "@number",
    ["@lsp.type.operator"] = "@operator",
    ["@lsp.type.parameter"] = "@variable.parameter",
    ["@lsp.type.property"] = "@property",
    ["@lsp.type.regexp"] = "@string.regexp",
    ["@lsp.type.string"] = "@string",
    ["@lsp.type.struct"] = "@type",
    ["@lsp.type.type"] = "@type",
    ["@lsp.type.typeParameter"] = "@type.definition",
    ["@lsp.type.variable"] = "@variable",
    ["@lsp.typemod.function.declaration"] = "@function",
    ["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.function.readonly"] = "@function",
    ["@lsp.typemod.method.declaration"] = "@function.method",
    ["@lsp.typemod.method.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.method.readonly"] = "@function.method",
    ["@lsp.typemod.operator.readonly"] = "@operator",
    ["@lsp.typemod.parameter.readonly"] = "@variable.parameter",
    ["@lsp.typemod.property.readonly"] = "@property",
    ["@lsp.typemod.type.declaration"] = "@type",
    ["@lsp.typemod.type.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.type.readonly"] = "@type",
    ["@lsp.typemod.variable.callable"] = "@function",
    ["@lsp.typemod.variable.declaration"] = "@variable",
    ["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
    ["@lsp.typemod.variable.global"] = "@variable",
    ["@lsp.typemod.variable.injected"] = "@variable",
    ["@lsp.typemod.variable.readonly"] = "@variable.member",
    ["@lsp.typemod.variable.static"] = "@variable",
  }
end

return { build = build }
