local function build(p, o)
  local util = require("synthwave3000.util")
  return {
    Comment = { fg = p.comment, italic = o.styles.comments.italic ~= false },
    Constant = { fg = p.orange },
    String = { fg = p.orange_bright },
    Character = { fg = p.orange },
    Number = { fg = p.orange },
    Boolean = { fg = p.orange },
    Float = { fg = p.orange },
    Identifier = { fg = p.pink },
    Function = { fg = p.cyan, bold = o.styles.functions.bold },
    Statement = { fg = p.yellow },
    Conditional = { fg = p.yellow, bold = o.styles.keywords.bold },
    Repeat = { fg = p.yellow, bold = o.styles.keywords.bold },
    Label = { fg = p.pink },
    Operator = { fg = p.yellow },
    Keyword = { fg = p.yellow, bold = o.styles.keywords.bold },
    Exception = { fg = p.red, bold = o.styles.keywords.bold },
    PreProc = { fg = p.purple },
    Include = { fg = p.green },
    Define = { fg = p.yellow },
    Macro = { fg = p.yellow },
    PreCondit = { fg = p.purple },
    Type = { fg = p.red, bold = o.styles.types.bold },
    StorageClass = { fg = p.red, bold = o.styles.types.bold },
    Structure = { fg = p.red, bold = o.styles.types.bold },
    Typedef = { fg = p.red, bold = o.styles.types.bold },
    Special = { fg = p.pink },
    SpecialChar = { fg = p.orange },
    Tag = { fg = p.green },
    Delimiter = { fg = p.fg_dim },
    SpecialComment = { fg = p.comment, italic = true },
    Debug = { fg = p.orange },
    Underlined = { underline = true },
    Ignore = { fg = p.fg_dim },
    Error = { fg = p.red, bold = true },
    Todo = { fg = p.yellow, bg = util.blend(p.yellow, p.bg, 0.15), bold = true },
  }
end

return { build = build }
