local function build(p, o)
  local groups = {
    ["@variable"] = { fg = p.pink },
    ["@variable.builtin"] = { fg = p.red },
    ["@variable.parameter"] = { fg = p.orange },
    ["@variable.member"] = { fg = p.pink },
    ["@constant"] = { fg = p.orange },
    ["@constant.builtin"] = { fg = p.orange },
    ["@constant.macro"] = { fg = p.yellow },
    ["@module"] = { fg = p.purple },
    ["@module.builtin"] = { fg = p.purple },
    ["@label"] = { fg = p.pink },
    ["@string"] = { fg = p.orange_bright },
    ["@string.documentation"] = { fg = p.green, italic = true },
    ["@string.regexp"] = { fg = p.orange },
    ["@string.escape"] = { fg = p.cyan },
    ["@string.special"] = { fg = p.green },
    ["@string.special.symbol"] = { fg = p.pink },
    ["@string.special.url"] = { fg = p.cyan, underline = true },
    ["@character"] = { fg = p.orange },
    ["@character.special"] = { fg = p.orange },
    ["@boolean"] = { fg = p.orange },
    ["@number"] = { fg = p.orange },
    ["@number.float"] = { fg = p.orange },
    ["@type"] = { fg = p.red, bold = o.styles.types.bold },
    ["@type.builtin"] = { fg = p.red, bold = o.styles.types.bold },
    ["@type.definition"] = { fg = p.red, bold = o.styles.types.bold },
    ["@attribute"] = { fg = p.yellow },
    ["@attribute.builtin"] = { fg = p.yellow },
    ["@property"] = { fg = p.pink },
    ["@function"] = { fg = p.cyan, bold = o.styles.functions.bold },
    ["@function.builtin"] = { fg = p.cyan, bold = o.styles.functions.bold },
    ["@function.call"] = { fg = p.cyan, bold = o.styles.functions.bold },
    ["@function.macro"] = { fg = p.yellow },
    ["@function.method"] = { fg = p.cyan, bold = o.styles.functions.bold },
    ["@function.method.call"] = { fg = p.cyan, bold = o.styles.functions.bold },
    ["@constructor"] = { fg = p.yellow },
    ["@operator"] = { fg = p.yellow },
    ["@keyword"] = { fg = p.yellow, bold = o.styles.keywords.bold },
    ["@keyword.coroutine"] = { fg = p.yellow, bold = o.styles.keywords.bold },
    ["@keyword.function"] = { fg = p.yellow, bold = o.styles.keywords.bold },
    ["@keyword.operator"] = { fg = p.yellow, bold = o.styles.keywords.bold },
    ["@keyword.import"] = { fg = p.green },
    ["@keyword.type"] = { fg = p.red, bold = o.styles.types.bold },
    ["@keyword.modifier"] = { fg = p.yellow, bold = o.styles.keywords.bold },
    ["@keyword.repeat"] = { fg = p.yellow, bold = o.styles.keywords.bold },
    ["@keyword.return"] = { fg = p.yellow, bold = o.styles.keywords.bold },
    ["@keyword.debug"] = { fg = p.orange },
    ["@keyword.exception"] = { fg = p.red, bold = o.styles.keywords.bold },
    ["@keyword.conditional"] = { fg = p.yellow, bold = o.styles.keywords.bold },
    ["@keyword.conditional.ternary"] = { fg = p.yellow, bold = o.styles.keywords.bold },
    ["@keyword.directive"] = { fg = p.purple },
    ["@keyword.directive.define"] = { fg = p.purple },
    ["@punctuation.delimiter"] = { fg = p.fg_dim },
    ["@punctuation.bracket"] = { fg = p.fg_dim },
    ["@punctuation.special"] = "@markup.list",
    ["@comment"] = { fg = p.comment, italic = o.styles.comments.italic ~= false },
    ["@comment.documentation"] = { fg = p.comment, italic = true },
    ["@comment.error"] = { fg = p.red, bold = true },
    ["@comment.warning"] = { fg = p.yellow },
    ["@comment.todo"] = { fg = p.orange, bold = true },
    ["@comment.note"] = { fg = p.cyan, italic = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = p.pink, bold = true },
    ["@markup.heading.1"] = { fg = p.pink, bold = true },
    ["@markup.heading.2"] = { fg = p.cyan, bold = true },
    ["@markup.heading.3"] = { fg = p.yellow, bold = true },
    ["@markup.heading.4"] = { fg = p.pink, bold = true },
    ["@markup.heading.5"] = { fg = p.cyan, bold = true },
    ["@markup.heading.6"] = { fg = p.yellow, bold = true },
    ["@markup.quote"] = { fg = p.fg_dim, italic = true },
    ["@markup.math"] = { fg = p.orange },
    ["@markup.environment"] = { fg = p.purple },
    ["@markup.link"] = { fg = p.cyan, underline = true },
    ["@markup.link.label"] = { fg = p.pink },
    ["@markup.link.url"] = { fg = p.cyan, underline = true },
    ["@markup.raw"] = { fg = p.green },
    ["@markup.raw.block"] = { fg = p.green },
    ["@markup.list"] = { fg = p.cyan },
    ["@markup.list.checked"] = { fg = p.green },
    ["@markup.list.unchecked"] = { fg = p.fg_dim },
    ["@diff.plus"] = { fg = p.green },
    ["@diff.minus"] = { fg = p.red },
    ["@diff.delta"] = { fg = p.yellow },
    ["@tag"] = { fg = p.green },
    ["@tag.builtin"] = { fg = p.red },
    ["@tag.attribute"] = { fg = p.yellow },
    ["@tag.delimiter"] = { fg = p.fg_dim },
  }

  local aliases = {
    ["@text"] = "@markup",
    ["@text.literal"] = "@markup.raw",
    ["@text.reference"] = "@markup.link",
    ["@text.title"] = "@markup.heading",
    ["@text.uri"] = "@markup.link.url",
    ["@text.underline"] = "@markup.underline",
    ["@text.todo"] = "@comment.todo",
    ["@text.note"] = "@comment.note",
    ["@text.warning"] = "@comment.warning",
    ["@text.danger"] = "@comment.error",
    ["@text.diff.add"] = "@diff.plus",
    ["@text.diff.delete"] = "@diff.minus",
    ["@string.regex"] = "@string.regexp",
    ["@parameter"] = "@variable.parameter",
    ["@field"] = "@variable.member",
    ["@namespace"] = "@module",
    ["@symbol"] = "@string.special.symbol",
  }

  for old, new in pairs(aliases) do
    groups[old] = new
  end

  return groups
end

return { build = build }
