local function build(p, o)
	local bg_panel = o.transparent and "NONE" or p.bg_panel
	return {
		BlinkCmpMenu = { fg = p.fg, bg = bg_panel },
		BlinkCmpMenuBorder = { fg = p.pink, bg = bg_panel },
		BlinkCmpMenuSelection = { fg = p.fg, bg = p.bg_highlight },
		BlinkCmpScrollBarThumb = { bg = p.selection },
		BlinkCmpScrollBarGutter = { bg = bg_panel },
		BlinkCmpLabel = { fg = p.fg },
		BlinkCmpLabelDeprecated = { fg = p.fg_dim, strikethrough = true },
		BlinkCmpLabelMatch = { fg = p.cyan, bold = true },
		BlinkCmpLabelDetail = { fg = p.fg_dim },
		BlinkCmpLabelDescription = { fg = p.fg_dim },
		BlinkCmpKind = { fg = p.fg_dim },
		BlinkCmpKindText = { fg = p.orange_bright },
		BlinkCmpKindMethod = { fg = p.cyan },
		BlinkCmpKindFunction = { fg = p.cyan },
		BlinkCmpKindConstructor = { fg = p.yellow },
		BlinkCmpKindField = { fg = p.pink },
		BlinkCmpKindVariable = { fg = p.pink },
		BlinkCmpKindClass = { fg = p.red },
		BlinkCmpKindInterface = { fg = p.red },
		BlinkCmpKindModule = { fg = p.purple },
		BlinkCmpKindProperty = { fg = p.pink },
		BlinkCmpKindUnit = { fg = p.orange },
		BlinkCmpKindValue = { fg = p.orange },
		BlinkCmpKindEnum = { fg = p.red },
		BlinkCmpKindKeyword = { fg = p.yellow },
		BlinkCmpKindSnippet = { fg = p.orange },
		BlinkCmpKindColor = { fg = p.pink },
		BlinkCmpKindFile = { fg = p.cyan },
		BlinkCmpKindReference = { fg = p.pink },
		BlinkCmpKindFolder = { fg = p.cyan },
		BlinkCmpKindEnumMember = { fg = p.red },
		BlinkCmpKindConstant = { fg = p.orange },
		BlinkCmpKindStruct = { fg = p.red },
		BlinkCmpKindEvent = { fg = p.yellow },
		BlinkCmpKindOperator = { fg = p.yellow },
		BlinkCmpKindTypeParameter = { fg = p.red },
		BlinkCmpSource = { fg = p.fg_dim },
		BlinkCmpGhostText = { fg = p.comment },
		BlinkCmpDoc = { fg = p.fg, bg = bg_panel },
		BlinkCmpDocBorder = { fg = p.pink, bg = bg_panel },
		BlinkCmpDocSeparator = { fg = p.pink },
		BlinkCmpDocCursorLine = { bg = p.bg_highlight },
		BlinkCmpSignatureHelp = { fg = p.fg, bg = bg_panel },
		BlinkCmpSignatureHelpBorder = { fg = p.pink, bg = bg_panel },
		BlinkCmpSignatureHelpActiveParameter = { fg = p.cyan, bold = true },
	}
end

return { build = build }
