local function build(p, o)
  local bg = o.transparent and "NONE" or (o.background or p.bg)
  local bg_dark = o.transparent and "NONE" or p.bg_dark
  local bg_darker = o.transparent and "NONE" or p.bg_darker
  return {
    BufferLineFill = { bg = bg_darker },
    BufferLineBackground = { fg = p.fg_dim, bg = bg_dark },
    BufferLineBufferVisible = { fg = p.fg_dim, bg = bg_dark },
    BufferLineBufferSelected = { fg = p.pink, bg = bg, bold = true },
    BufferLineCloseButton = { fg = p.fg_dim, bg = bg_dark },
    BufferLineCloseButtonVisible = { fg = p.fg_dim, bg = bg_dark },
    BufferLineCloseButtonSelected = { fg = p.red, bg = bg },
    BufferLineModified = { fg = p.orange, bg = bg_dark },
    BufferLineModifiedVisible = { fg = p.orange, bg = bg_dark },
    BufferLineModifiedSelected = { fg = p.orange, bg = bg },
    BufferLineIndicatorSelected = { fg = p.pink, bg = bg },
    BufferLineSeparator = { fg = p.pink, bg = bg_darker },
    BufferLineSeparatorVisible = { fg = p.pink, bg = bg_dark },
    BufferLineSeparatorSelected = { fg = p.pink, bg = bg },
    BufferLineTab = { fg = p.fg_dim, bg = bg_darker },
    BufferLineTabSelected = { fg = p.pink, bg = bg },
    BufferLineNumbers = { fg = p.fg_dim, bg = bg_dark },
    BufferLineNumbersVisible = { fg = p.fg_dim, bg = bg_dark },
    BufferLineNumbersSelected = { fg = p.pink, bg = bg },
    BufferLineOffsetSeparator = { fg = p.pink, bg = bg_darker },
    BufferLineDuplicate = { fg = p.purple, bg = bg_dark },
    BufferLineDuplicateVisible = { fg = p.purple, bg = bg_dark },
    BufferLineDuplicateSelected = { fg = p.purple, bg = bg },
    BufferLinePick = { fg = p.green, bg = bg_dark },
    BufferLinePickVisible = { fg = p.green, bg = bg_dark },
    BufferLinePickSelected = { fg = p.green, bg = bg },
    BufferLineDiagnostic = { fg = p.cyan, bg = bg_dark },
    BufferLineDiagnosticVisible = { fg = p.cyan, bg = bg_dark },
    BufferLineDiagnosticSelected = { fg = p.cyan, bg = bg },
    BufferLineError = { fg = p.red, bg = bg_dark },
    BufferLineErrorVisible = { fg = p.red, bg = bg_dark },
    BufferLineErrorSelected = { fg = p.red, bg = bg },
    BufferLineWarning = { fg = p.yellow, bg = bg_dark },
    BufferLineWarningVisible = { fg = p.yellow, bg = bg_dark },
    BufferLineWarningSelected = { fg = p.yellow, bg = bg },
    BufferLineInfo = { fg = p.cyan, bg = bg_dark },
    BufferLineInfoVisible = { fg = p.cyan, bg = bg_dark },
    BufferLineInfoSelected = { fg = p.cyan, bg = bg },
    BufferLineHint = { fg = p.comment, bg = bg_dark },
    BufferLineHintVisible = { fg = p.comment, bg = bg_dark },
    BufferLineHintSelected = { fg = p.comment, bg = bg },
    BufferLineIndicatorVisible = { fg = p.pink, bg = bg_dark },
    BufferLineTruncMarker = { fg = p.fg_dim },
  }
end

return { build = build }
