local function build(p, o)
	local bg = o.transparent and "NONE" or (o.background or p.bg)
	return {
		MiniIndentscopeSymbol = { fg = p.comment },
		MiniStatuslineModeNormal = { fg = p.bg, bg = p.pink, bold = true },
		MiniStatuslineModeInsert = { fg = p.bg, bg = p.cyan, bold = true },
		MiniStatuslineModeVisual = { fg = p.bg, bg = p.purple, bold = true },
		MiniStatuslineModeReplace = { fg = p.bg, bg = p.orange, bold = true },
		MiniStatuslineModeCommand = { fg = p.bg, bg = p.yellow, bold = true },
		MiniStatuslineModeOther = { fg = p.bg, bg = p.comment, bold = true },
		MiniStatuslineDevinfo = { fg = p.fg_dim, bg = p.bg_dark },
		MiniStatuslineFilename = { fg = p.fg, bg = p.bg_dark },
		MiniStatuslineFileinfo = { fg = p.fg_dim, bg = p.bg_dark },
		MiniStatuslineInactive = { fg = p.fg_dim, bg = p.bg_darker },
		MiniTablineCurrent = { fg = p.pink, bg = p.bg, bold = true },
		MiniTablineVisible = { fg = p.fg, bg = p.bg_dark },
		MiniTablineHidden = { fg = p.fg_dim, bg = p.bg_darker },
		MiniTablineModifiedCurrent = { fg = p.orange, bg = p.bg },
		MiniTablineModifiedVisible = { fg = p.orange, bg = p.bg_dark },
		MiniTablineModifiedHidden = { fg = p.orange, bg = p.bg_darker },
		MiniTablineFill = { bg = p.bg_darker },
		MiniCursorword = { underline = true },
		MiniCursorwordCurrent = { underline = true },
		MiniHipatternsTodo = { fg = p.yellow, bg = p.bg_highlight, bold = true },
		MiniHipatternsNote = { fg = p.cyan, bg = p.bg_highlight },
		MiniHipatternsFixme = { fg = p.orange, bg = p.bg_highlight, bold = true },
		MiniHipatternsHack = { fg = p.purple, bg = p.bg_highlight },
		MiniPickPrompt = { fg = p.cyan },
		MiniPickMatchCurrent = { fg = p.fg, bg = p.bg_highlight },
		MiniPickMatchMarked = { fg = p.pink, bold = true },
		MiniPickMatchRanges = { fg = p.cyan, bold = true },
		MiniPickNormal = { fg = p.fg, bg = bg },
		MiniPickBorder = { fg = p.pink },
		MiniPickBorderBusy = { fg = p.pink },
		MiniPickBorderText = { fg = p.pink },
		MiniPickIconDirectory = { fg = p.cyan },
		MiniPickIconFile = { fg = p.fg },
		MiniPickHeader = { fg = p.cyan, bold = true },
		MiniPickPreviewLine = { bg = p.bg_highlight },
		MiniPickPreviewRegion = { bg = p.selection },
		MiniPickPromptCaret = { fg = p.pink },
		MiniPickPromptPrefix = { fg = p.pink },
		MiniFilesBorder = { fg = p.pink },
		MiniFilesBorderModified = { fg = p.pink },
		MiniFilesCursorLine = { bg = p.bg_highlight },
		MiniFilesDirectory = { fg = p.cyan },
		MiniFilesFile = { fg = p.fg },
		MiniFilesNormal = { fg = p.fg, bg = bg },
		MiniFilesTitle = { fg = p.pink },
		MiniFilesTitleFocused = { fg = p.cyan, bold = true },
		MiniJump = { fg = p.pink, bold = true },
		MiniJump2dDim = { fg = p.comment },
		MiniJump2dSpot = { fg = p.pink, bold = true },
		MiniJump2dSpotAhead = { fg = p.cyan, bold = true },
		MiniJump2dSpotUnique = { fg = p.green, bold = true },
		MiniTrailspace = { bg = p.bg_highlight },
		MiniDiffSignAdd = { fg = p.green },
		MiniDiffSignChange = { fg = p.yellow },
		MiniDiffSignDelete = { fg = p.red },
		MiniDiffOverAdd = { fg = p.green, bg = require("synthwave3000.util").blend(p.green, bg, 0.15) },
		MiniDiffOverChange = { fg = p.yellow, bg = require("synthwave3000.util").blend(p.yellow, bg, 0.15) },
		MiniDiffOverContext = { bg = p.bg_highlight },
		MiniDiffOverDelete = { fg = p.red, bg = require("synthwave3000.util").blend(p.red, bg, 0.15) },
		MiniStarterCurrent = { bg = p.bg_highlight },
		MiniStarterFooter = { fg = p.comment, italic = true },
		MiniStarterHeader = { fg = p.pink, bold = true },
		MiniStarterInactive = { fg = p.comment },
		MiniStarterItem = { fg = p.fg },
		MiniStarterItemBullet = { fg = p.pink },
		MiniStarterItemPrefix = { fg = p.cyan },
		MiniStarterSection = { fg = p.cyan, bold = true },
		MiniStarterQuery = { fg = p.cyan },
		MiniNotifyBorder = { fg = p.pink },
		MiniNotifyNormal = { fg = p.fg, bg = p.bg_dark },
		MiniNotifyTitle = { fg = p.cyan, bold = true },
		MiniClueBorder = { fg = p.pink },
		MiniClueDescGroup = { fg = p.cyan, bold = true },
		MiniClueDescSingle = { fg = p.fg },
		MiniClueNextKey = { fg = p.pink },
		MiniClueNextKeyWithPostkeys = { fg = p.cyan },
		MiniClueSeparator = { fg = p.pink },
		MiniClueTitle = { fg = p.cyan, bold = true },
		MiniIconsAzure = { fg = p.blue },
		MiniIconsBlue = { fg = p.blue },
		MiniIconsCyan = { fg = p.cyan },
		MiniIconsGreen = { fg = p.green },
		MiniIconsGrey = { fg = p.comment },
		MiniIconsOrange = { fg = p.orange },
		MiniIconsPurple = { fg = p.purple },
		MiniIconsRed = { fg = p.red },
		MiniIconsYellow = { fg = p.yellow },
		MiniTestEmphasis = { bold = true },
		MiniTestFail = { fg = p.red, bold = true },
		MiniTestPass = { fg = p.green, bold = true },
		MiniMapNormal = { fg = p.fg_dim, bg = p.bg_darker },
		MiniMapSymbolCount = { fg = p.comment },
		MiniMapSymbolLine = { fg = p.fg_dim },
		MiniMapSymbolView = { fg = p.pink },
	}
end

return { build = build }
