local function build(p, o)
  return {
    SnacksNormal = { fg = p.fg, bg = p.bg_dark },
    SnacksNormalNC = { fg = p.fg, bg = p.bg_dark },
    SnacksWinBar = { fg = p.fg, bg = p.bg_dark },
    SnacksWinBarNC = { fg = p.fg_dim, bg = p.bg_darker },
    SnacksBackdrop = { bg = p.bg_darker },
    SnacksDashboardNormal = { fg = p.fg, bg = p.bg },
    SnacksDashboardDesc = { fg = p.fg_dim },
    SnacksDashboardFile = { fg = p.fg },
    SnacksDashboardDir = { fg = p.cyan },
    SnacksDashboardFooter = { fg = p.comment, italic = true },
    SnacksDashboardHeader = { fg = p.pink, bold = true },
    SnacksDashboardIcon = { fg = p.pink },
    SnacksDashboardKey = { fg = p.cyan, bold = true },
    SnacksDashboardTerminal = { fg = p.green },
    SnacksDashboardSpecial = { fg = p.yellow },
    SnacksDashboardTitle = { fg = p.cyan, bold = true },
    SnacksIndent = { fg = p.bg_highlight },
    SnacksIndentScope = { fg = p.comment },
    SnacksIndentChunk = { fg = p.pink },
    SnacksNotifierInfo = { fg = p.cyan },
    SnacksNotifierWarn = { fg = p.yellow },
    SnacksNotifierError = { fg = p.red },
    SnacksNotifierDebug = { fg = p.comment },
    SnacksNotifierTrace = { fg = p.purple },
    SnacksNotifierIconInfo = { fg = p.cyan },
    SnacksNotifierIconWarn = { fg = p.yellow },
    SnacksNotifierIconError = { fg = p.red },
    SnacksPickerBorder = { fg = p.bg_highlight },
    SnacksPickerInput = { fg = p.fg, bg = p.bg_panel },
    SnacksPickerList = { fg = p.fg, bg = p.bg },
    SnacksPickerPreview = { fg = p.fg, bg = p.bg },
    SnacksPickerMatch = { fg = p.cyan, bold = true },
    SnacksPickerSelected = { fg = p.pink, bold = true },
  }
end

return { build = build }
