local function build(p, o)
  return {
    SnacksNormal = { fg = p.fg, bg = p.bg_dark },
    SnacksNormalNC = { fg = p.fg, bg = p.bg_dark },
    SnacksWinBar = { fg = p.fg, bg = p.bg_dark },
    SnacksWinBarNC = { fg = p.fg_dim, bg = p.bg_darker },
    SnacksTitle = { fg = p.cyan, bold = true },
    SnacksFooter = { fg = p.fg_dim },
    SnacksFooterDesc = { fg = p.fg_dim },
    SnacksFooterKey = { fg = p.pink },
    SnacksWinKey = { fg = p.yellow },
    SnacksWinKeySep = { fg = p.comment },
    SnacksWinKeyDesc = { fg = p.fg },
    SnacksWinSeparator = { fg = p.bg_highlight },
    SnacksBackdrop = { bg = p.bg_darker },
    SnacksDashboardNormal = { fg = p.fg, bg = p.bg },
    SnacksDashboardDesc = { fg = p.fg_dim },
    SnacksDashboardFile = { fg = p.fg },
    SnacksDashboardDir = { fg = p.cyan },
    SnacksDashboardFooter = { fg = p.comment, italic = true },
    SnacksDashboardHeader = { fg = p.pink, bold = true },
    SnacksDashboardIcon = { fg = p.pink },
    SnacksDashboardKey = { fg = p.cyan, bold = true },
    SnacksDashboardTerminal = { fg = p.green },
    SnacksDashboardSpecial = { fg = p.yellow },
    SnacksDashboardTitle = { fg = p.cyan, bold = true },
    SnacksIndent = { fg = p.bg_highlight },
    SnacksIndentScope = { fg = p.comment },
    SnacksIndentChunk = { fg = p.pink },
    SnacksIndent1 = { fg = p.pink },
    SnacksIndent2 = { fg = p.red },
    SnacksIndent3 = { fg = p.orange },
    SnacksIndent4 = { fg = p.yellow },
    SnacksIndent5 = { fg = p.green },
    SnacksIndent6 = { fg = p.cyan },
    SnacksIndent7 = { fg = p.blue },
    SnacksIndent8 = { fg = p.purple },
    SnacksNotifierInfo = { fg = p.cyan },
    SnacksNotifierWarn = { fg = p.yellow },
    SnacksNotifierError = { fg = p.red },
    SnacksNotifierDebug = { fg = p.comment },
    SnacksNotifierTrace = { fg = p.purple },
    SnacksNotifierIconInfo = { fg = p.cyan },
    SnacksNotifierIconWarn = { fg = p.yellow },
    SnacksNotifierIconError = { fg = p.red },
    SnacksNotifierIconDebug = { fg = p.comment },
    SnacksNotifierIconTrace = { fg = p.purple },
    SnacksNotifierBorderInfo = { fg = p.cyan },
    SnacksNotifierBorderWarn = { fg = p.yellow },
    SnacksNotifierBorderError = { fg = p.red },
    SnacksNotifierBorderDebug = { fg = p.comment },
    SnacksNotifierBorderTrace = { fg = p.purple },
    SnacksNotifierTitleInfo = { fg = p.cyan },
    SnacksNotifierTitleWarn = { fg = p.yellow },
    SnacksNotifierTitleError = { fg = p.red },
    SnacksNotifierTitleDebug = { fg = p.comment },
    SnacksNotifierTitleTrace = { fg = p.purple },
    SnacksNotifierFooterInfo = { fg = p.cyan },
    SnacksNotifierFooterWarn = { fg = p.yellow },
    SnacksNotifierFooterError = { fg = p.red },
    SnacksNotifierFooterDebug = { fg = p.comment },
    SnacksNotifierFooterTrace = { fg = p.purple },
    SnacksNotifierHistory = { fg = p.fg, bg = p.bg_dark },
    SnacksNotifierHistoryTitle = { fg = p.cyan, bold = true },
    SnacksNotifierHistoryDateTime = { fg = p.comment },
    SnacksNotifierMinimal = { fg = p.fg, bg = p.bg_dark },
    SnacksPickerBorder = { fg = p.bg_highlight },
    SnacksPickerInput = { fg = p.fg, bg = p.bg_panel },
    SnacksPickerList = { fg = p.fg, bg = p.bg },
    SnacksPickerPreview = { fg = p.fg, bg = p.bg },
    SnacksPickerMatch = { fg = p.cyan, bold = true },
    SnacksPickerSelected = { fg = p.pink, bold = true },
    SnacksPickerPrompt = { fg = p.cyan },
    SnacksPickerSearch = { bg = p.bg_highlight },
    SnacksPickerLabel = { fg = p.fg },
    SnacksPickerTotals = { fg = p.comment },
    SnacksPickerFile = { fg = p.fg },
    SnacksPickerLink = { fg = p.cyan },
    SnacksPickerLinkBroken = { fg = p.red },
    SnacksPickerDirectory = { fg = p.cyan },
    SnacksPickerPathIgnored = { fg = p.comment },
    SnacksPickerPathHidden = { fg = p.comment },
    SnacksPickerDir = { fg = p.comment },
    SnacksPickerToggle = { fg = p.cyan },
    SnacksPickerDimmed = { fg = p.comment },
    SnacksPickerRow = { fg = p.fg_dim },
    SnacksPickerCol = { fg = p.comment },
    SnacksPickerComment = { fg = p.comment },
    SnacksPickerDesc = { fg = p.fg_dim },
    SnacksPickerDelim = { fg = p.fg_dim },
    SnacksPickerSpinner = { fg = p.pink },
    SnacksPickerCmd = { fg = p.cyan },
    SnacksPickerCmdBuiltin = { fg = p.yellow },
    SnacksPickerUnselected = { fg = p.fg_dim },
    SnacksPickerIdx = { fg = p.orange },
    SnacksPickerBold = { bold = true },
    SnacksPickerTree = { fg = p.comment },
    SnacksPickerItalic = { italic = true },
    SnacksPickerCode = { fg = p.pink },
    SnacksPickerGitCommit = { fg = p.fg_dim },
    SnacksPickerGitBreaking = { fg = p.red },
    SnacksPickerGitDetached = { fg = p.orange },
    SnacksPickerGitBranch = { fg = p.pink },
    SnacksPickerGitBranchCurrent = { fg = p.green, bold = true },
    SnacksPickerGitDate = { fg = p.comment },
    SnacksPickerGitIssue = { fg = p.orange },
    SnacksPickerGitAuthor = { fg = p.cyan },
    SnacksPickerGitType = { fg = p.purple },
    SnacksPickerGitScope = { italic = true, fg = p.fg_dim },
    SnacksPickerGitStatus = { fg = p.fg_dim },
    SnacksPickerGitStatusAdded = { fg = p.green },
    SnacksPickerGitStatusModified = { fg = p.yellow },
    SnacksPickerGitStatusDeleted = { fg = p.red },
    SnacksPickerGitStatusRenamed = { fg = p.cyan },
    SnacksPickerGitStatusCopied = { fg = p.cyan },
    SnacksPickerGitStatusUntracked = { fg = p.comment },
    SnacksPickerGitStatusIgnored = { fg = p.comment },
    SnacksPickerGitStatusUnmerged = { fg = p.orange },
    SnacksPickerGitStatusStaged = { fg = p.green },
    SnacksPickerTime = { fg = p.comment },
    SnacksPickerRule = { fg = p.comment },
    SnacksPickerInputSearch = { fg = p.cyan },
    SnacksPickerPickWin = { bg = p.bg_highlight },
    SnacksPickerPickWinCurrent = { bg = p.selection },
    SnacksStatusColumnMark = { fg = p.cyan },
  }
end

return { build = build }
